# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1026, 712)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label_image_esse = QtWidgets.QLabel(self.centralWidget)
        self.label_image_esse.setGeometry(QtCore.QRect(100, 40, 241, 191))
        self.label_image_esse.setText("")
        self.label_image_esse.setObjectName("label_image_esse")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(130, 260, 71, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_image_marlboro = QtWidgets.QLabel(self.centralWidget)
        self.label_image_marlboro.setGeometry(QtCore.QRect(400, 40, 281, 191))
        self.label_image_marlboro.setText("")
        self.label_image_marlboro.setObjectName("label_image_marlboro")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(430, 260, 71, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton_select_esse = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_select_esse.setGeometry(QtCore.QRect(90, 290, 161, 51))
        self.pushButton_select_esse.setObjectName("pushButton_select_esse")
        self.pushButton_select_marlboro = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_select_marlboro.setGeometry(QtCore.QRect(380, 290, 171, 51))
        self.pushButton_select_marlboro.setObjectName("pushButton_select_marlboro")
        self.label_image_bohem = QtWidgets.QLabel(self.centralWidget)
        self.label_image_bohem.setGeometry(QtCore.QRect(60, 340, 261, 201))
        self.label_image_bohem.setText("")
        self.label_image_bohem.setObjectName("label_image_bohem")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(130, 560, 71, 31))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.pushButton_selelct_bohem = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_selelct_bohem.setGeometry(QtCore.QRect(90, 590, 161, 51))
        self.pushButton_selelct_bohem.setObjectName("pushButton_selelct_bohem")
        self.label_image_mevius = QtWidgets.QLabel(self.centralWidget)
        self.label_image_mevius.setGeometry(QtCore.QRect(350, 350, 281, 221))
        self.label_image_mevius.setText("")
        self.label_image_mevius.setObjectName("label_image_mevius")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(430, 560, 71, 31))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.pushButton_select_mevius = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_select_mevius.setGeometry(QtCore.QRect(380, 590, 181, 51))
        self.pushButton_select_mevius.setObjectName("pushButton_select_mevius")
        self.lineEdit_notice = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_notice.setGeometry(QtCore.QRect(680, 310, 321, 21))
        self.lineEdit_notice.setText("")
        self.lineEdit_notice.setObjectName("lineEdit_notice")
        self.label_image_logo = QtWidgets.QLabel(self.centralWidget)
        self.label_image_logo.setGeometry(QtCore.QRect(550, -20, 461, 351))
        self.label_image_logo.setText("")
        self.label_image_logo.setObjectName("label_image_logo")
        self.lineEdit_money = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_money.setGeometry(QtCore.QRect(680, 341, 321, 20))
        self.lineEdit_money.setObjectName("lineEdit_money")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(680, 370, 332, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.pushButton_return = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_return.setObjectName("pushButton_return")
        self.gridLayout.addWidget(self.pushButton_return, 0, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 3, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 3, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 3, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.pushButton_insert = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_insert.setObjectName("pushButton_insert")
        self.gridLayout.addWidget(self.pushButton_insert, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 1, 0, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 0, 1, 1, 1)
        self.pushButton_insert_done = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_insert_done.setGeometry(QtCore.QRect(690, 430, 111, 32))
        self.pushButton_insert_done.setObjectName("pushButton_insert_done")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(600, 310, 71, 21))
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(600, 340, 71, 21))
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1026, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuCigaratte_Vending_machine = QtWidgets.QMenu(self.menuBar)
        self.menuCigaratte_Vending_machine.setObjectName("menuCigaratte_Vending_machine")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuCigaratte_Vending_machine.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "4500$"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "5000$"))
        self.pushButton_select_esse.setText(_translate("MainWindow", "Select"))
        self.pushButton_select_marlboro.setText(_translate("MainWindow", "Select"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "4800$"))
        self.pushButton_selelct_bohem.setText(_translate("MainWindow", "Selelct"))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "4500$"))
        self.pushButton_select_mevius.setText(_translate("MainWindow", "Select"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_return.setText(_translate("MainWindow", "Return"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_insert.setText(_translate("MainWindow", "Insert"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_insert_done.setText(_translate("MainWindow", "Insert Done"))
        self.plainTextEdit_5.setPlainText(_translate("MainWindow", "Notice"))
        self.plainTextEdit_6.setPlainText(_translate("MainWindow", "Money"))
        self.menuCigaratte_Vending_machine.setTitle(_translate("MainWindow", "Cigaratte Vending machine"))

